import type { BodyType, CarPart, DiagnosticCodeInfo } from '@/types'

export const BODY_TYPES: { value: BodyType; label: string }[] = [
  { value: 'sedan', label: 'Sedan' },
  { value: 'suv', label: 'SUV' },
  { value: 'truck', label: 'Truck' },
  { value: 'coupe', label: 'Coupe' },
  { value: 'hatchback', label: 'Hatchback' },
]

export const CAR_MAKES = [
  'Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge',
  'Ford', 'GMC', 'Honda', 'Hyundai', 'Infiniti', 'Jeep', 'Kia', 'Lexus',
  'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan',
  'Ram', 'Subaru', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo',
]

export const CAR_COLORS = [
  { name: 'Midnight Blue', value: '#1e3a5f' },
  { name: 'Silver', value: '#94a3b8' },
  { name: 'Pearl White', value: '#f1f5f9' },
  { name: 'Jet Black', value: '#0f172a' },
  { name: 'Racing Red', value: '#dc2626' },
  { name: 'Forest Green', value: '#166534' },
  { name: 'Champagne Gold', value: '#ca8a04' },
  { name: 'Graphite Gray', value: '#475569' },
  { name: 'Orange Burst', value: '#ea580c' },
  { name: 'Deep Purple', value: '#6b21a8' },
]

export const PART_LABELS: Record<CarPart, string> = {
  engine: 'Engine',
  transmission: 'Transmission',
  exhaust: 'Exhaust System',
  fuel_system: 'Fuel System',
  cooling: 'Cooling System',
  electrical: 'Electrical System',
  brakes: 'Brakes',
  suspension: 'Suspension',
  tires: 'Tires / Wheels',
  catalytic_converter: 'Catalytic Converter',
  o2_sensor: 'O2 Sensor',
  air_intake: 'Air Intake',
  battery: 'Battery',
  alternator: 'Alternator',
  starter: 'Starter Motor',
  radiator: 'Radiator',
  ac_compressor: 'A/C Compressor',
  steering: 'Steering',
  abs_module: 'ABS Module',
  spark_plugs: 'Spark Plugs',
  ignition_coil: 'Ignition Coil',
  maf_sensor: 'MAF Sensor',
  throttle_body: 'Throttle Body',
  evap_system: 'EVAP System',
}

export const DIAGNOSTIC_CODES: DiagnosticCodeInfo[] = [
  {
    code: 'P0300',
    description: 'Random/Multiple Cylinder Misfire Detected',
    affectedPart: 'engine',
    severity: 'high',
    commonCauses: ['Worn spark plugs', 'Bad ignition coils', 'Vacuum leak', 'Low fuel pressure', 'Clogged fuel injectors'],
    fixSteps: [
      'Scan tool: note which cylinders misfire (P0301–P0308 if present).',
      'Inspect spark plugs — replace if worn, fouled, or wrong gap.',
      'Swap ignition coils between cylinders; clear codes and retest.',
      'Check for vacuum leaks around intake manifold and PCV hoses.',
      'Test fuel pressure at rail; replace fuel filter if below spec.',
      'If misfire persists on one cylinder, perform compression test.',
    ],
    partsNeeded: ['Spark plugs (set)', 'Ignition coils (as needed)', 'Fuel filter'],
    estimatedCost: '$80 – $450',
    difficulty: 'moderate',
  },
  {
    code: 'P0301',
    description: 'Cylinder 1 Misfire Detected',
    affectedPart: 'spark_plugs',
    severity: 'high',
    commonCauses: ['Bad spark plug on cylinder 1', 'Failed coil pack', 'Clogged injector', 'Low compression'],
    fixSteps: [
      'Remove and inspect cylinder 1 spark plug for oil fouling or wear.',
      'Replace spark plug; torque to manufacturer spec.',
      'Swap cylinder 1 ignition coil with another cylinder — retest.',
      'If misfire follows coil, replace ignition coil.',
      'Run fuel injector cleaner or test injector flow on cylinder 1.',
      'Compression test cylinder 1 if issue remains.',
    ],
    partsNeeded: ['Spark plug (1)', 'Ignition coil (if faulty)'],
    estimatedCost: '$25 – $180',
    difficulty: 'easy',
  },
  {
    code: 'P0420',
    description: 'Catalyst System Efficiency Below Threshold (Bank 1)',
    affectedPart: 'catalytic_converter',
    severity: 'medium',
    commonCauses: ['Failing catalytic converter', 'Bad downstream O2 sensor', 'Engine running rich/lean', 'Exhaust leak'],
    fixSteps: [
      'Verify no exhaust leaks before the catalytic converter.',
      'Check live O2 sensor data — upstream should oscillate, downstream should be steady.',
      'Address any misfire or fuel trim codes first (they damage cats).',
      'If O2 sensors are old (>100k mi), replace downstream sensor first.',
      'If data confirms cat failure, replace catalytic converter.',
      'Clear codes and drive cycle to confirm fix.',
    ],
    partsNeeded: ['Downstream O2 sensor', 'Catalytic converter (if confirmed bad)'],
    estimatedCost: '$150 – $2,500',
    difficulty: 'hard',
  },
  {
    code: 'P0171',
    description: 'System Too Lean (Bank 1)',
    affectedPart: 'air_intake',
    severity: 'medium',
    commonCauses: ['Vacuum leak', 'Dirty MAF sensor', 'Weak fuel pump', 'Clogged fuel filter', 'Bad O2 sensor'],
    fixSteps: [
      'Inspect all vacuum lines and intake boot for cracks or disconnects.',
      'Clean MAF sensor with MAF-specific cleaner — do not touch sensor wire.',
      'Check fuel pressure at idle and under load.',
      'Replace fuel filter if overdue.',
      'Smoke test intake if vacuum leak is suspected but not visible.',
      'Monitor short-term and long-term fuel trim after repairs.',
    ],
    partsNeeded: ['MAF sensor cleaner', 'Fuel filter', 'Vacuum hose (if cracked)'],
    estimatedCost: '$30 – $350',
    difficulty: 'moderate',
  },
  {
    code: 'P0172',
    description: 'System Too Rich (Bank 1)',
    affectedPart: 'fuel_system',
    severity: 'medium',
    commonCauses: ['Leaking fuel injector', 'Faulty MAF sensor', 'Bad O2 sensor', 'High fuel pressure', 'Clogged air filter'],
    fixSteps: [
      'Check and replace air filter if dirty.',
      'Inspect MAF sensor readings vs. expected airflow.',
      'Test fuel pressure — replace regulator if over spec.',
      'Check for leaking injectors (fuel smell, black smoke).',
      'Inspect O2 sensor voltage — stuck high indicates rich condition.',
      'Clear adaptations and retest after repair.',
    ],
    partsNeeded: ['Air filter', 'Fuel pressure regulator', 'O2 sensor (if faulty)'],
    estimatedCost: '$40 – $400',
    difficulty: 'moderate',
  },
  {
    code: 'P0128',
    description: 'Coolant Thermostat Below Regulating Temperature',
    affectedPart: 'cooling',
    severity: 'low',
    commonCauses: ['Stuck-open thermostat', 'Low coolant', 'Coolant temp sensor fault'],
    fixSteps: [
      'Verify coolant level and check for leaks.',
      'Monitor coolant temp — should reach 195–220°F within 10 minutes.',
      'If temp stays low, replace thermostat and gasket.',
      'Bleed cooling system of air after refill.',
      'Retest — code should clear after 2 drive cycles.',
    ],
    partsNeeded: ['Thermostat', 'Coolant', 'Thermostat gasket/O-ring'],
    estimatedCost: '$25 – $120',
    difficulty: 'easy',
  },
  {
    code: 'P0442',
    description: 'EVAP System Leak Detected (Small Leak)',
    affectedPart: 'evap_system',
    severity: 'low',
    commonCauses: ['Loose or missing gas cap', 'Cracked EVAP hose', 'Failed purge valve', 'Leaking charcoal canister'],
    fixSteps: [
      'Inspect gas cap seal — replace cap if cracked or worn.',
      'Tighten gas cap until it clicks; clear code and wait 2 drive cycles.',
      'Visually inspect EVAP hoses near fuel tank and engine bay.',
      'Smoke test EVAP system if cap replacement does not fix it.',
      'Test purge valve and vent solenoid with scan tool.',
      'Replace leaking component identified by smoke test.',
    ],
    partsNeeded: ['Gas cap', 'EVAP purge valve', 'EVAP hose'],
    estimatedCost: '$15 – $250',
    difficulty: 'easy',
  },
  {
    code: 'P0455',
    description: 'EVAP System Leak Detected (Large Leak)',
    affectedPart: 'evap_system',
    severity: 'medium',
    commonCauses: ['Missing gas cap', 'Disconnected EVAP hose', 'Failed vent valve', 'Damaged charcoal canister'],
    fixSteps: [
      'Confirm gas cap is present and seals properly.',
      'Trace all EVAP lines from tank to engine — look for disconnects.',
      'Inspect filler neck and tank for damage or rust holes.',
      'Perform smoke test to pinpoint large leak location.',
      'Replace damaged hose, valve, or canister as identified.',
    ],
    partsNeeded: ['Gas cap', 'EVAP vent valve', 'Charcoal canister', 'EVAP hoses'],
    estimatedCost: '$20 – $600',
    difficulty: 'moderate',
  },
  {
    code: 'P0134',
    description: 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)',
    affectedPart: 'o2_sensor',
    severity: 'medium',
    commonCauses: ['Failed upstream O2 sensor', 'Wiring damage', 'Blown fuse', 'Exhaust leak near sensor'],
    fixSteps: [
      'Locate Bank 1 Sensor 1 (upstream, before catalytic converter).',
      'Inspect wiring harness for damage, corrosion, or disconnect.',
      'Check O2 sensor fuse in fuse box.',
      'Test sensor heater circuit resistance with multimeter.',
      'Replace upstream O2 sensor if heater or signal circuit is failed.',
      'Clear code and verify sensor oscillates between 0.1–0.9V at idle.',
    ],
    partsNeeded: ['Upstream O2 sensor (Bank 1)', 'O2 sensor socket'],
    estimatedCost: '$50 – $200',
    difficulty: 'moderate',
  },
  {
    code: 'P0101',
    description: 'MAF Sensor Circuit Range/Performance Problem',
    affectedPart: 'maf_sensor',
    severity: 'medium',
    commonCauses: ['Dirty MAF sensor', 'Intake air leak after MAF', 'Failed MAF sensor', 'Clogged air filter'],
    fixSteps: [
      'Replace air filter if dirty.',
      'Clean MAF sensor with dedicated MAF cleaner spray.',
      'Inspect intake duct between MAF and throttle body for cracks.',
      'Compare MAF grams/second reading to spec at idle with scan tool.',
      'Replace MAF sensor if readings are erratic or out of range after cleaning.',
    ],
    partsNeeded: ['MAF sensor cleaner', 'Air filter', 'MAF sensor (if needed)'],
    estimatedCost: '$15 – $350',
    difficulty: 'easy',
  },
  {
    code: 'P0121',
    description: 'Throttle/Pedal Position Sensor Range/Performance Problem',
    affectedPart: 'throttle_body',
    severity: 'medium',
    commonCauses: ['Dirty throttle body', 'Failed TPS', 'Wiring issue', 'Carbon buildup'],
    fixSteps: [
      'Clean throttle body and bore with throttle body cleaner.',
      'Inspect throttle plate for carbon buildup and sticking.',
      'Check TPS voltage sweep with scan tool while opening throttle.',
      'Inspect connector and wiring for corrosion.',
      'Relearn idle after cleaning (scan tool or key cycle procedure).',
      'Replace throttle body assembly if TPS is integrated and faulty.',
    ],
    partsNeeded: ['Throttle body cleaner', 'Throttle body gasket', 'Throttle body (if needed)'],
    estimatedCost: '$20 – $500',
    difficulty: 'moderate',
  },
  {
    code: 'P0507',
    description: 'Idle Air Control System RPM Higher Than Expected',
    affectedPart: 'air_intake',
    severity: 'low',
    commonCauses: ['Vacuum leak', 'Dirty throttle body', 'Failed IAC valve', 'PCV valve stuck open'],
    fixSteps: [
      'Clean throttle body and perform idle relearn.',
      'Check for vacuum leaks using spray or smoke test.',
      'Inspect PCV valve — replace if rattling or stuck.',
      'Verify no aftermarket intakes causing unmetered air.',
      'Check idle RPM spec and adjust if vehicle has idle screw.',
    ],
    partsNeeded: ['Throttle body cleaner', 'PCV valve', 'Vacuum hose'],
    estimatedCost: '$15 – $150',
    difficulty: 'easy',
  },
  {
    code: 'P0700',
    description: 'Transmission Control System Malfunction',
    affectedPart: 'transmission',
    severity: 'high',
    commonCauses: ['Low transmission fluid', 'Internal transmission fault', 'TCM failure', 'Wiring to transmission'],
    fixSteps: [
      'Check transmission fluid level and condition — top off or change if burnt.',
      'Scan transmission module for specific codes (P07xx series).',
      'Inspect transmission wiring harness at bell housing for damage.',
      'Check for TSBs related to your make/model/transmission.',
      'If fluid is good and wiring intact, internal diagnosis needed.',
      'Consider transmission specialist for rebuild or valve body repair.',
    ],
    partsNeeded: ['Transmission fluid', 'Transmission filter kit'],
    estimatedCost: '$100 – $4,000+',
    difficulty: 'professional',
  },
  {
    code: 'P0562',
    description: 'System Voltage Low',
    affectedPart: 'battery',
    severity: 'medium',
    commonCauses: ['Weak battery', 'Failing alternator', 'Corroded terminals', 'Parasitic draw'],
    fixSteps: [
      'Test battery voltage — should be 12.4V+ at rest.',
      'Load test battery; replace if fails.',
      'Test alternator output — should be 13.5–14.5V running.',
      'Clean battery terminals and ground connections.',
      'Check drive belt tension on alternator.',
      'Replace alternator if output is low under load.',
    ],
    partsNeeded: ['Battery', 'Alternator', 'Battery terminal cleaner'],
    estimatedCost: '$100 – $450',
    difficulty: 'easy',
  },
  {
    code: 'P0606',
    description: 'ECM/PCM Processor Fault',
    affectedPart: 'electrical',
    severity: 'critical',
    commonCauses: ['ECU internal failure', 'Water damage to ECU', 'Voltage spike', 'Software corruption'],
    fixSteps: [
      'Check battery voltage and ground connections to ECU first.',
      'Inspect ECU connector for corrosion or water intrusion.',
      'Try clearing code — if returns immediately, ECU may be failing.',
      'Check for related codes and TSBs for ECU reflash.',
      'Attempt ECU software update at dealership if available.',
      'Replace ECU and program to vehicle VIN if hardware fault confirmed.',
    ],
    partsNeeded: ['ECU/PCM (if replacement needed)', 'ECU programming service'],
    estimatedCost: '$300 – $1,500',
    difficulty: 'professional',
  },
  {
    code: 'P0500',
    description: 'Vehicle Speed Sensor Malfunction',
    affectedPart: 'electrical',
    severity: 'medium',
    commonCauses: ['Failed VSS', 'Damaged tone ring', 'Wiring fault', 'Instrument cluster issue'],
    fixSteps: [
      'Locate vehicle speed sensor (transmission or wheel hub depending on vehicle).',
      'Inspect sensor wiring and connector.',
      'Test VSS output with multimeter or scan tool while rotating wheel.',
      'Check tone ring for missing teeth or debris.',
      'Replace VSS if no signal output.',
    ],
    partsNeeded: ['Vehicle speed sensor'],
    estimatedCost: '$30 – $150',
    difficulty: 'moderate',
  },
  {
    code: 'P0401',
    description: 'EGR Flow Insufficient Detected',
    affectedPart: 'exhaust',
    severity: 'medium',
    commonCauses: ['Clogged EGR valve', 'Carbon-clogged EGR passages', 'Failed EGR solenoid'],
    fixSteps: [
      'Remove and inspect EGR valve for carbon buildup.',
      'Clean EGR passages in intake manifold.',
      'Test EGR solenoid vacuum operation.',
      'Replace EGR valve gasket on reassembly.',
      'Clear code and verify EGR position sensor responds on scan tool.',
    ],
    partsNeeded: ['EGR valve', 'EGR gasket', 'Carb/intake cleaner'],
    estimatedCost: '$50 – $300',
    difficulty: 'moderate',
  },
  {
    code: 'P0316',
    description: 'Misfire Detected on Startup (First 1000 Revolutions)',
    affectedPart: 'ignition_coil',
    severity: 'high',
    commonCauses: ['Weak battery causing slow crank', 'Worn spark plugs', 'Failing coils', 'Low compression when cold'],
    fixSteps: [
      'Test battery and confirm strong crank speed on cold start.',
      'Replace spark plugs if due or worn.',
      'Check for pending misfire codes on specific cylinders.',
      'Inspect ignition coils for cracks or heat damage.',
      'Perform cold-start compression test if misfire persists.',
    ],
    partsNeeded: ['Spark plugs', 'Ignition coils', 'Battery (if weak)'],
    estimatedCost: '$50 – $400',
    difficulty: 'moderate',
  },
  {
    code: 'C0035',
    description: 'Left Front Wheel Speed Sensor Circuit',
    affectedPart: 'abs_module',
    severity: 'medium',
    commonCauses: ['Failed wheel speed sensor', 'Damaged tone ring', 'Broken wire in harness'],
    fixSteps: [
      'Inspect LF wheel speed sensor at hub for damage or debris.',
      'Check resistance of sensor — compare to spec (typically 1–2.5 kΩ).',
      'Inspect wiring along suspension for chafing.',
      'Clean sensor tip and tone ring.',
      'Replace sensor if open circuit or out-of-spec resistance.',
    ],
    partsNeeded: ['Wheel speed sensor (LF)'],
    estimatedCost: '$30 – $120',
    difficulty: 'moderate',
  },
  {
    code: 'P0017',
    description: 'Crankshaft/Camshaft Position Correlation (Bank 1 Sensor B)',
    affectedPart: 'engine',
    severity: 'critical',
    commonCauses: ['Stretched timing chain', 'Failed VVT solenoid', 'Cam/crank sensor fault', 'Low oil level'],
    fixSteps: [
      'Verify engine oil level and condition — low oil causes VVT issues.',
      'Check for TSBs on timing chain for your engine.',
      'Monitor cam/crank correlation with scan tool at idle and 2500 RPM.',
      'Inspect VVT solenoid — clean or replace if stuck.',
      'If chain stretch confirmed, timing chain kit replacement required.',
      'Do not continue driving — engine damage risk is high.',
    ],
    partsNeeded: ['VVT solenoid', 'Timing chain kit', 'Cam/crank sensors'],
    estimatedCost: '$200 – $2,500',
    difficulty: 'professional',
  },
  {
    code: 'P0113',
    description: 'Intake Air Temperature Sensor 1 Circuit High Input',
    affectedPart: 'air_intake',
    severity: 'low',
    commonCauses: ['Failed IAT sensor', 'Short to voltage in wiring', 'Disconnected sensor'],
    fixSteps: [
      'Locate IAT sensor (often integrated in MAF housing).',
      'Inspect connector for loose pins or corrosion.',
      'Test sensor resistance — compare to temperature/resistance chart.',
      'Check wiring for short to 5V reference.',
      'Replace IAT sensor if out of spec.',
    ],
    partsNeeded: ['IAT sensor or MAF/IAT assembly'],
    estimatedCost: '$20 – $200',
    difficulty: 'easy',
  },
  {
    code: 'P0400',
    description: 'Exhaust Gas Recirculation Flow Malfunction',
    affectedPart: 'exhaust',
    severity: 'medium',
    commonCauses: ['Stuck EGR valve', 'Clogged passages', 'Vacuum line leak to EGR'],
    fixSteps: [
      'Test EGR valve movement with vacuum pump or scan tool command.',
      'Remove valve and clean carbon deposits.',
      'Clear carbon from intake EGR ports.',
      'Verify vacuum supply to EGR solenoid.',
      'Replace EGR valve if diaphragm is torn or motor fails.',
    ],
    partsNeeded: ['EGR valve', 'EGR gasket'],
    estimatedCost: '$50 – $250',
    difficulty: 'moderate',
  },
  {
    code: 'P0520',
    description: 'Engine Oil Pressure Sensor/Switch Circuit Malfunction',
    affectedPart: 'engine',
    severity: 'high',
    commonCauses: ['Failed oil pressure sensor', 'Actual low oil pressure', 'Wiring fault'],
    fixSteps: [
      'Verify oil level immediately — do not run engine if oil is low.',
      'If oil level OK, test actual oil pressure with mechanical gauge.',
      'If mechanical pressure is good, replace oil pressure sensor.',
      'If pressure is low, inspect for worn bearings or failing oil pump.',
      'Check sensor wiring and connector for oil contamination.',
    ],
    partsNeeded: ['Oil pressure sensor', 'Engine oil', 'Oil filter'],
    estimatedCost: '$30 – $1,500',
    difficulty: 'moderate',
  },
  {
    code: 'P2181',
    description: 'Cooling System Performance Problem',
    affectedPart: 'radiator',
    severity: 'medium',
    commonCauses: ['Low coolant', 'Failing water pump', 'Clogged radiator', 'Stuck thermostat'],
    fixSteps: [
      'Pressure test cooling system for external leaks.',
      'Check coolant level and test freeze protection.',
      'Feel upper/lower radiator hoses — both should heat evenly.',
      'Inspect water pump for weep hole leakage or play.',
      'Flush radiator if flow is restricted.',
      'Replace thermostat and/or water pump as diagnosed.',
    ],
    partsNeeded: ['Coolant', 'Thermostat', 'Water pump', 'Radiator (if clogged)'],
    estimatedCost: '$50 – $800',
    difficulty: 'moderate',
  },
]

export function lookupDiagnosticCode(input: string): DiagnosticCodeInfo | null {
  const normalized = input.trim().toUpperCase().replace(/\s/g, '')
  return DIAGNOSTIC_CODES.find((d) => d.code === normalized) ?? null
}

export function searchDiagnosticCodes(query: string): DiagnosticCodeInfo[] {
  const q = query.trim().toLowerCase()
  if (!q) return DIAGNOSTIC_CODES
  return DIAGNOSTIC_CODES.filter(
    (d) =>
      d.code.toLowerCase().includes(q) ||
      d.description.toLowerCase().includes(q) ||
      PART_LABELS[d.affectedPart].toLowerCase().includes(q),
  )
}
